/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onemillionworlds_tamarin_openxrbindings_Library */

#ifndef _Included_com_onemillionworlds_tamarin_openxrbindings_Library
#define _Included_com_onemillionworlds_tamarin_openxrbindings_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onemillionworlds_tamarin_openxrbindings_Library
 * Method:    xrEnumerateApiLayerProperties
 * Signature: (ILcom/onemillionworlds/tamarin/openxrbindings/XrApiLayerProperties/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onemillionworlds_tamarin_openxrbindings_Library_xrEnumerateApiLayerProperties
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
