name: Java release with Gradle

on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Grant execute permission for upload script
      run: chmod +x .github/scripts/upload_central.sh

    - name: Build with Gradle
      run: ./gradlew build

    - name: Decode GPG key
      run: echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" | base64 --decode > ./secring.gpg

    - name: Configure Gradle user properties
      run: |
        mkdir -p ~/.gradle
        echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> ~/.gradle/gradle.properties
        echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> ~/.gradle/gradle.properties
        echo "signing.secretKeyRingFile=$GITHUB_WORKSPACE/secring.gpg" >> ~/.gradle/gradle.properties
        echo "ossrhUsername=${{ secrets.OSSRH_USERNAME }}" >> ~/.gradle/gradle.properties
        echo "ossrhPassword=${{ secrets.OSSRH_PASSWORD }}" >> ~/.gradle/gradle.properties
        # Central Publisher Portal credentials (uses same account as OSSRH)
        echo "centralUsername=${{ secrets.OSSRH_USERNAME }}" >> ~/.gradle/gradle.properties
        echo "centralPassword=${{ secrets.OSSRH_PASSWORD }}" >> ~/.gradle/gradle.properties

    - name: Prepare Central bundle (stage + zip)
      run: ./gradlew :android-native:prepareCentralBundle

    - name: Upload bundle via Central Publisher API (USER_MANAGED)
      run: .github/scripts/upload_central.sh "android-native/build/central-bundle.zip"
      env:
        CENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        CENTRAL_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

    - name: Tag and update version
      run: |
        # Extract current version from gradle.properties
        VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2)
        echo "Current version: $VERSION"
        
        # Create and push the tag for the current version
        git tag "v$VERSION"
        git push origin "v$VERSION"
        
        # Increment version for the next cycle (bumps last numeric segment)
        NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        echo "New version: $NEW_VERSION"
        
        # Update gradle.properties with the new version
        sed -i "s/^version=$VERSION/version=$NEW_VERSION/" gradle.properties
        
        # Commit the change
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gradle.properties
        git commit -m "Increment version to $NEW_VERSION [skip ci]" || echo "No changes to commit"
        
        # Push the commit
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
